/**
 * NRC township codes, by state/region.
 *
 * Every Myanmar NRC is <state>/<township><type><6 digits>, e.g.
 * 12/OUKAMA(N)123456. The township component is a code, not free text —
 * there are a few hundred of them and they are printed on the card in
 * Burmese, so a person copying one into a Latin text box is guessing at a
 * transliteration. That is the typo this table exists to remove.
 *
 * `code` is the Latin form this platform stores and hashes. `codeMm` is the
 * Burmese form actually printed on the card, and is what the operator should
 * be matching against — the picker shows both.
 *
 * Generated from github.com/htetoozin/Myanmar-NRC. Not exhaustive: township
 * codes change as townships are created or renamed, so the NRC input accepts
 * a code that is not in this list rather than blocking a real person whose
 * card we have not catalogued.
 */

export interface NrcTownship {
  /** Latin transliteration, upper case. The stored form. */
  code: string;
  /** Burmese code as printed on the card, e.g. အဂယ. */
  codeMm: string;
  /** Burmese township name, where the source had one. */
  nameMm: string;
}

/** 417 township codes across states 1-14. */
export const NRC_TOWNSHIPS: Readonly<Record<number, readonly NrcTownship[]>> = {
  1: [
    { code: "AHGAYA", codeMm: "အဂယ", nameMm: "အင်ဂျန်းယန်" },
    { code: "BAMANA", codeMm: "ဗမန", nameMm: "ဗန်းမော်" },
    { code: "DAPHAYA", codeMm: "ဒဖယ", nameMm: "ဒေါ့ဖုန်းယန်" },
    { code: "HAPANA", codeMm: "ဟပန", nameMm: "ဟိုပင်" },
    { code: "KAMANA", codeMm: "ကမန", nameMm: "ကာမီ" },
    { code: "KAMATA", codeMm: "ကမတ", nameMm: "ကာမိုင်း" },
    { code: "KAPATA", codeMm: "ကပတ", nameMm: "ကန်ပိုက်တီ" },
    { code: "KHALAPHA", codeMm: "ခလဖ", nameMm: "ခေါင်လန်ဖူး" },
    { code: "KHAPHANA", codeMm: "ခဖန", nameMm: "ချီဖွေ" },
    { code: "LAGANA", codeMm: "လဂန", nameMm: "လွယ်ဂျယ်" },
    { code: "MAKANA", codeMm: "မကန", nameMm: "မြစ်ကြီးနား" },
    { code: "MAKATA", codeMm: "မကတ", nameMm: "မိုးကောင်း" },
    { code: "MAKHABA", codeMm: "မခဘ", nameMm: "မချမ်းဘော" },
    { code: "MALANA", codeMm: "မလန", nameMm: "မြို့လှ" },
    { code: "MAMANA", codeMm: "မမန", nameMm: "မိုးမောက်" },
    { code: "MANYANA", codeMm: "မညန", nameMm: "မိုးညင်း" },
    { code: "MASANA", codeMm: "မစန", nameMm: "မံစီ" },
    { code: "NAMANA", codeMm: "နမန", nameMm: "နောင်မွန်း" },
    { code: "PANADA", codeMm: "ပနဒ", nameMm: "ပန်နန်းဒင်" },
    { code: "PATAAH", codeMm: "ပတအ", nameMm: "ပူတာအို" },
    { code: "PAWANA", codeMm: "ပဝန", nameMm: "ပန်ဝါ" },
    { code: "PHAKANA", codeMm: "ဖကန", nameMm: "ဖားကန့်" },
    { code: "SABANA", codeMm: "ဆဘန", nameMm: "ဆင်ဘို" },
    { code: "SADANA", codeMm: "ဆဒန", nameMm: "ဆဒုံး" },
    { code: "SALANA", codeMm: "ဆလန", nameMm: "ဆော့လော" },
    { code: "SAPABA", codeMm: "ဆပဘ", nameMm: "ဆွမ်ပရာဘွမ်" },
    { code: "TANANA", codeMm: "တနန", nameMm: "တနိုင်း" },
    { code: "WAMANA", codeMm: "ဝမန", nameMm: "ဝင်းမော်" },
    { code: "YABAYA", codeMm: "ရဘယ", nameMm: "ရှင်ဘွေယန်" },
    { code: "YAKANA", codeMm: "ရကန", nameMm: "ရွှေကူ" },
  ],
  2: [
    { code: "BALAKHA", codeMm: "ဘလခ", nameMm: "ဘော်လခဲ" },
    { code: "DAMASA", codeMm: "ဒမဆ", nameMm: "ဒီမောဆိုး" },
    { code: "LAKANA", codeMm: "လကန", nameMm: "လွိုင်ကော်" },
    { code: "MASANA", codeMm: "မဆန", nameMm: "မယ်ဆည်နန်" },
    { code: "PHASANA", codeMm: "ဖဆန", nameMm: "ဖားဆောင်း" },
    { code: "PHAYASA", codeMm: "ဖရဆ", nameMm: "ဖရူးဆိုး" },
    { code: "YATANA", codeMm: "ရတန", nameMm: "ရှားတော်" },
    { code: "YATHANA", codeMm: "ရသန", nameMm: "ရွာသစ်" },
  ],
  3: [
    { code: "BAAHNA", codeMm: "ဘအန", nameMm: "ဘားအံ" },
    { code: "BAGALA", codeMm: "ဘဂလ", nameMm: "ဘောဂလိ" },
    { code: "BATHASA", codeMm: "ဘသဆ", nameMm: "ဘုရားသုံးဆူ" },
    { code: "KADANA", codeMm: "ကဒန", nameMm: "ကျုံဒိုး" },
    { code: "KAKAYA", codeMm: "ကကရ", nameMm: "ကော့ကရိတ်" },
    { code: "KAMAMA", codeMm: "ကမမ", nameMm: "ကမမောင်း" },
    { code: "KASAKA", codeMm: "ကဆက", nameMm: "ကြာအင်းဆိပ်ကြီး" },
    { code: "LABANA", codeMm: "လဘန", nameMm: "လှိုင်းဘွဲ့" },
    { code: "LATHANA", codeMm: "လသန", nameMm: "လိပ်သို" },
    { code: "MAWATA", codeMm: "မဝတ", nameMm: "မြဝတီ" },
    { code: "PHAAHNA", codeMm: "ဖအန", nameMm: "ဖားအံ" },
    { code: "PHAPANA", codeMm: "ဖပန", nameMm: "ဖျာပွန်" },
    { code: "SAKALA", codeMm: "စကလ", nameMm: "စုကလိ" },
    { code: "THATAKA", codeMm: "သတက", nameMm: "သံတောင်ကြီး" },
    { code: "THATANA", codeMm: "သတန", nameMm: "သံတောင်" },
    { code: "WALAMA", codeMm: "ဝလမ", nameMm: "ဝေါလေမြိုင်" },
    { code: "YAYATHA", codeMm: "ရရသ", nameMm: "ရှမ်းရွာသစ်" },
  ],
  4: [
    { code: "HAKHANA", codeMm: "ဟခန", nameMm: "ဟားခါး" },
    { code: "HTATALA", codeMm: "ထတလ", nameMm: "ထန်တလန်" },
    { code: "KAKHANA", codeMm: "ကခန", nameMm: "ကျီခါး" },
    { code: "KAPALA", codeMm: "ကပလ", nameMm: "ကန်ပက်လက်" },
    { code: "MATANA", codeMm: "မတန", nameMm: "မင်းတပ်" },
    { code: "MATAPA", codeMm: "မတပ", nameMm: "မတူပီ" },
    { code: "PALAWA", codeMm: "ပလဝ", nameMm: "ပလက်ဝ" },
    { code: "PHALANA", codeMm: "ဖလန", nameMm: "ဖလမ်း" },
    { code: "SAMANA", codeMm: "ဆမန", nameMm: "ဆမီး" },
    { code: "TATANA", codeMm: "တတန", nameMm: "တီးတိန်" },
    { code: "TAZANA", codeMm: "တဇန", nameMm: "တွန်းဇံ" },
    { code: "YAKHADA", codeMm: "ရခဒ", nameMm: "ရိဒ်ခေါဒါရ်" },
    { code: "YAZANA", codeMm: "ရဇန", nameMm: "ရေဇွာ" },
  ],
  5: [
    { code: "AHTANA", codeMm: "အတန", nameMm: "အင်းတော်" },
    { code: "AHYATA", codeMm: "အရတ", nameMm: "အရာတော်" },
    { code: "BAMANA", codeMm: "ဗမန", nameMm: "ဗန်းမောက်" },
    { code: "BATALA", codeMm: "ဘတလ", nameMm: "ဘုတလင်" },
    { code: "DAHANA", codeMm: "ဒဟန", nameMm: "ဒုံဟီး" },
    { code: "DAPAYA", codeMm: "ဒပယ", nameMm: "ဒီပဲယင်း" },
    { code: "HAMALA", codeMm: "ဟမလ", nameMm: "ဟုမ္မလင်း" },
    { code: "HTAKHANA", codeMm: "ထခန", nameMm: "ထီးချိုင့်" },
    { code: "HTAPAKHA", codeMm: "ထပခ", nameMm: "ထန်ပါခွေ" },
    { code: "KABALA", codeMm: "ကဘန", nameMm: "ကန့်ဘလူ" },
    { code: "KALAHTA", codeMm: "ကလထ", nameMm: "ကလေး" },
    { code: "KALANA", codeMm: "ကလန", nameMm: "ကျွန်းလှ" },
    { code: "KALATA", codeMm: "ကလတ", nameMm: "ကောလင်း" },
    { code: "KALAWA", codeMm: "ကလဝ", nameMm: "ကလေးဝ" },
    { code: "KAMANA", codeMm: "ကမန", nameMm: "ကျောက်မြောင်း" },
    { code: "KANANA", codeMm: "ကနန", nameMm: "ကနီ" },
    { code: "KATHANA", codeMm: "ကသန", nameMm: "ကသာ" },
    { code: "KHAOUNA", codeMm: "ခဥန", nameMm: "ချောင်းဦး" },
    { code: "KHAOUTA", codeMm: "ခဥတ", nameMm: "ခင်ဦး" },
    { code: "KHAPANA", codeMm: "ခပန", nameMm: "ခမ်းပတ်" },
    { code: "KHATANA", codeMm: "ခတန", nameMm: "ခန္တီး" },
    { code: "LAHANA", codeMm: "လဟန", nameMm: "လဟယ်" },
    { code: "LAYANA", codeMm: "လရန", nameMm: "လေရှီး" },
    { code: "MAKANA", codeMm: "မကန", nameMm: "မင်းကင်း" },
    { code: "MALANA", codeMm: "မလန", nameMm: "မော်လိုက်" },
    { code: "MAMANA", codeMm: "မမန", nameMm: "မြောင်" },
    { code: "MAPALA", codeMm: "မပလ", nameMm: "မိုပိုင်းလွတ်" },
    { code: "MATHANA", codeMm: "မသန", nameMm: "မြို့သစ်" },
    { code: "MAYANA", codeMm: "မရန", nameMm: "မုံရွာ" },
    { code: "NAYANA", codeMm: "နယန", nameMm: "နန်းယွန်း" },
    { code: "NGAZANA", codeMm: "ငဇန", nameMm: "ငါးန်ဇွန်" },
    { code: "PALANA", codeMm: "ပလန", nameMm: "ပုလဲ" },
    { code: "PALANBA", codeMm: "ပလဘ", nameMm: "ပင်လယ်ဘူး" },
    { code: "PASANA", codeMm: "ပဆန", nameMm: "ပန်ဆောင်" },
    { code: "PHAPANA", codeMm: "ဖပန", nameMm: "ဖောင်ပျင်း" },
    { code: "SAKANA", codeMm: "စကန", nameMm: "စစ်ကိုင်း" },
    { code: "SALAKA", codeMm: "ဆလက", nameMm: "ဆားလင်းကြီး" },
    { code: "SAMAYA", codeMm: "ဆမရ", nameMm: "ဆွမ္မရာ" },
    { code: "TAMANA", codeMm: "တမန", nameMm: "တမူး" },
    { code: "TASANA", codeMm: "တဆန", nameMm: "တန့်ဆည်" },
    { code: "WALANA", codeMm: "ဝလန", nameMm: "ဝက်လက်" },
    { code: "WATHANA", codeMm: "ဝသန", nameMm: "ဝမ်းသို" },
    { code: "YABANA", codeMm: "ရဘန", nameMm: "ရွှေဘို" },
    { code: "YAMAPA", codeMm: "ယမပ", nameMm: "ယင်းမာပင်" },
    { code: "YAOUNA", codeMm: "ရဥန", nameMm: "ရေဦး" },
    { code: "YATHAKA", codeMm: "ရသက", nameMm: "ရွာသစ်ကြီး" },
  ],
  6: [
    { code: "BAPANA", codeMm: "ဘပန", nameMm: "ဘုတ်ပြင်း" },
    { code: "HTAWANA", codeMm: "ထဝန", nameMm: "ထားဝယ်" },
    { code: "KALAAH", codeMm: "ကလအ", nameMm: "ကလိန်အောင်" },
    { code: "KASANA", codeMm: "ကစန", nameMm: "ကျွန်းစု" },
    { code: "KATHANA", codeMm: "ကသန", nameMm: "ကော့သောင်း" },
    { code: "KAYAYA", codeMm: "ကရရ", nameMm: "ကရသူရိ" },
    { code: "KHAMAKA", codeMm: "ခမက", nameMm: "ခမောက်ကြီး" },
    { code: "LALANA", codeMm: "လလန", nameMm: "လောင်းလုံ" },
    { code: "MAAHNA", codeMm: "မအန", nameMm: "မြိတ်အနောက်" },
    { code: "MAAHYA", codeMm: "မအရ", nameMm: "မြိတ်အရှေ့" },
    { code: "MAMANA", codeMm: "မမန", nameMm: "မြိတ်" },
    { code: "MATANA", codeMm: "မတန", nameMm: "မေတ္တာမြို့နယ်ခွဲ" },
    { code: "NGAYAKA", codeMm: "ငရက", nameMm: "ငရုတ်ကောင်း" },
    { code: "PAKAMA", codeMm: "ပကမ", nameMm: "ပြည်ကြီးမဏ္ဍိုင်" },
    { code: "PALANA", codeMm: "ပလန", nameMm: "ပုလော" },
    { code: "PALATA", codeMm: "ပလတ", nameMm: "ပလောက်" },
    { code: "TANATHA", codeMm: "တနသ", nameMm: "တနသာၤရီ" },
    { code: "TATHAYA", codeMm: "တသရ", nameMm: "တနသာၤရီ" },
    { code: "THAYAKHA", codeMm: "သရခ", nameMm: "သရက်ချောင်း" },
    { code: "YAPHANA", codeMm: "ရဖန", nameMm: "ရေဖြူ" },
  ],
  7: [
    { code: "AHPHANA", codeMm: "အဖန", nameMm: "အုတ်ဖို" },
    { code: "AHTANA", codeMm: "အတန", nameMm: "အုတ်တွင်း" },
    { code: "DAOUNA", codeMm: "ဒဥန", nameMm: "ဒိုက်ဦး" },
    { code: "HTATAPA", codeMm: "ထတပ", nameMm: "ထန်းတပင်" },
    { code: "KAKANA", codeMm: "ကကန", nameMm: "ကျောက်ကြီး" },
    { code: "KAPAKA", codeMm: "ကပက", nameMm: "ကြို့ပင်ကောက်" },
    { code: "KATAKHA", codeMm: "ကတခ", nameMm: "ကျောက်တံခါး" },
    { code: "KATATA", codeMm: "ကတတ", nameMm: "ကေတုမတီ" },
    { code: "KAWANA", codeMm: "ကဝန", nameMm: "ကဝ" },
    { code: "LAPATA", codeMm: "လပတ", nameMm: "လက်ပံတန်း" },
    { code: "MADANA", codeMm: "မဒန", nameMm: "မဒေါက်" },
    { code: "MALANA", codeMm: "မလန", nameMm: "မင်းလှ" },
    { code: "MANYANA", codeMm: "မညန", nameMm: "မိုးညို" },
    { code: "NATALA", codeMm: "နတလ", nameMm: "နတ်တလင်း" },
    { code: "NYALAPA", codeMm: "ညလပ", nameMm: "ညောင်လေးပင်" },
    { code: "PAKHANA", codeMm: "ပခန", nameMm: "ပဲခူး" },
    { code: "PAKHATA", codeMm: "ပခန", nameMm: "ပေါက်ခေါင်း" },
    { code: "PAMANA", codeMm: "ပမန", nameMm: "ပြည်" },
    { code: "PANAKA", codeMm: "ပနက", nameMm: "ပဲနွယ်ကုန်း" },
    { code: "PATALA", codeMm: "ပတလ", nameMm: "ပေါင်းတလည်" },
    { code: "PATANA", codeMm: "ပတန", nameMm: "ပန်တောင်း" },
    { code: "PATASA", codeMm: "ပတစ", nameMm: "ပြွန်တဆာ" },
    { code: "PATATA", codeMm: "ပတတ", nameMm: "ပေါင်းတည်" },
    { code: "PHAMANA", codeMm: "ဖမန", nameMm: "ဖြူး" },
    { code: "TANGANA", codeMm: "တငန", nameMm: "တောင်ငူ" },
    { code: "THAKANA", codeMm: "သကန", nameMm: "သဲကုန်း" },
    { code: "THANAPA", codeMm: "သနပ", nameMm: "သနပ်ပင်" },
    { code: "THASANA", codeMm: "သဆန", nameMm: "သုံးဆယ်" },
    { code: "THAWATA", codeMm: "သဝတ", nameMm: "သာယာဝတီ" },
    { code: "WAMANA", codeMm: "ဝမန", nameMm: "ဝေါ" },
    { code: "YAKANA", codeMm: "ရကန", nameMm: "ရွှေကျင်" },
    { code: "YATANA", codeMm: "ရတန", nameMm: "ရွှေတောင်" },
    { code: "YATAYA", codeMm: "ရတရ", nameMm: "ရေတာရှည်" },
    { code: "ZAKANA", codeMm: "ဇကန", nameMm: "ဇီးကုန်း" },
  ],
  8: [
    { code: "AHLANA", codeMm: "အလန", nameMm: "အောင်လံ" },
    { code: "GAGANA", codeMm: "ဂဂန", nameMm: "ဂန့်ဂေါ" },
    { code: "HTALANA", codeMm: "ထလန", nameMm: "ထီးလင်း" },
    { code: "KAHTANA", codeMm: "ကထန", nameMm: "ကျောက်ထု" },
    { code: "KAMANA", codeMm: "ကမန", nameMm: "ကံမ" },
    { code: "KHAMANA", codeMm: "ခမန", nameMm: "ချောက်" },
    { code: "MABANA", codeMm: "မဘန", nameMm: "မင်းဘူး" },
    { code: "MAHTANA", codeMm: "မထန", nameMm: "မြေထဲ" },
    { code: "MAKANA", codeMm: "မကန", nameMm: "မကွေး" },
    { code: "MALANA", codeMm: "မလန", nameMm: "မင်းလှ" },
    { code: "MAMANA", codeMm: "မမန", nameMm: "မြိုင်" },
    { code: "MATANA", codeMm: "မတန", nameMm: "မင်းတုန်း" },
    { code: "MATHANA", codeMm: "မသန", nameMm: "မြို့သစ်" },
    { code: "NAMANA", codeMm: "နမန", nameMm: "နတ်မောက်" },
    { code: "NGAPHANA", codeMm: "ငဖန", nameMm: "ငါးဖယ်" },
    { code: "PAKHAKA", codeMm: "ပခက", nameMm: "ပခုက္ကူ" },
    { code: "PAMANA", codeMm: "ပမန", nameMm: "ပေါက်" },
    { code: "PAPHANA", codeMm: "ပဖန", nameMm: "ပွင့်ဖြူ" },
    { code: "SAKANA", codeMm: "စကန", nameMm: "စကု" },
    { code: "SALANA", codeMm: "စလန", nameMm: "စလင်း" },
    { code: "SAMANA", codeMm: "ဆမန", nameMm: "ဆော" },
    { code: "SAPAWA", codeMm: "ဆပဝ", nameMm: "ဆင်ပေါင်ဝဲ" },
    { code: "SAPHANA", codeMm: "ဆဖန", nameMm: "ဆိပ်ဖြူ" },
    { code: "SATAYA", codeMm: "စတရ", nameMm: "စေတုတ္တရာ" },
    { code: "TATAKA", codeMm: "တတက", nameMm: "တောင်တွင်းကြီး" },
    { code: "THAYANA", codeMm: "သရန", nameMm: "သရက်" },
    { code: "YANAKHA", codeMm: "ရနခ", nameMm: "ရေနံချောင်း" },
    { code: "YASAKA", codeMm: "ရစက", nameMm: "ရေစကြို" },
  ],
  9: [
    { code: "AHMAYA", codeMm: "အမရ", nameMm: "အမရပူရ" },
    { code: "AHMAZA", codeMm: "အမဇ", nameMm: "အောင်မြေသာဇံ" },
    { code: "DAKHATHA", codeMm: "ဒခသ", nameMm: "ဒက္ခိဏသီရိ" },
    { code: "KAPATA", codeMm: "ကပတ", nameMm: "ကျောက်ပန်းတောင်း" },
    { code: "KASANA", codeMm: "ကဆန", nameMm: "ကျောက်ဆည်" },
    { code: "KHAAHSA", codeMm: "ခအဇ", nameMm: "ချမ်းအေးသာစံ" },
    { code: "KHAAHZA", codeMm: "ခအစ", nameMm: "ချမ်းအေးသာစည်" },
    { code: "KHAMASA", codeMm: "ခမစ", nameMm: "ချမ်းမြသာစည်" },
    { code: "LAWANA", codeMm: "လဝန", nameMm: "လယ်ဝေး" },
    { code: "MAHAMA", codeMm: "မဟမ", nameMm: "မဟာအောင်မြေ" },
    { code: "MAHTALA", codeMm: "မထလ", nameMm: "မိတ္ထီလာ" },
    { code: "MAKANA", codeMm: "မကန", nameMm: "မိုးကုတ်" },
    { code: "MAKHANA", codeMm: "မခန", nameMm: "မြင်းခြံ" },
    { code: "MALANA", codeMm: "မလန", nameMm: "မလိူင်" },
    { code: "MAMANA", codeMm: "မမန", nameMm: "မေမြို့" },
    { code: "MANAMA", codeMm: "မနမ", nameMm: "မန်းနောက်မြောက်" },
    { code: "MANATA", codeMm: "မနတ", nameMm: "မန်းနောက်တောင်" },
    { code: "MATAYA", codeMm: "မတရ", nameMm: "မတ္တရာ" },
    { code: "MATHANA", codeMm: "မသန", nameMm: "မြစ်သား" },
    { code: "MAYAMA", codeMm: "မရမ", nameMm: "မန်းရှေ့မြောက်" },
    { code: "MAYATA", codeMm: "မရတ", nameMm: "မန်းရှေ့တောင်" },
    { code: "NAHTAKA", codeMm: "နထက", nameMm: "နွားထိုးကြီး" },
    { code: "NGATAYA", codeMm: "ငသရ", nameMm: "င့ါသရောက်" },
    { code: "NGAZANA", codeMm: "ငဇန", nameMm: "ငါန်းဇွန်" },
    { code: "NYAOUNA", codeMm: "ညဥန", nameMm: "ညောင်ဦး" },
    { code: "OOTAYA", codeMm: "ဥတသ", nameMm: "ဥတ္တရသီရိ" },
    { code: "OUTATHA", codeMm: "ဥတသ", nameMm: "ဥတ္တရသီရိ" },
    { code: "PABANA", codeMm: "ပဖန", nameMm: "ပျော်ဖွယ်" },
    { code: "PABATHA", codeMm: "ပဗသ", nameMm: "ပုဗ္ဗသီရိ" },
    { code: "PAKAKHA", codeMm: "ပကခ", nameMm: "ပြည်ကြီးတံခွန်" },
    { code: "PALANA", codeMm: "ပလန", nameMm: "ပုလိပ်" },
    { code: "PAMANA", codeMm: "ပမန", nameMm: "ပျဉ်းမနား" },
    { code: "PAOULA", codeMm: "ပဥလ", nameMm: "ပြင်ဦးလွင်" },
    { code: "PATHAKA", codeMm: "ပသက", nameMm: "ပုသိမ်ကြီး" },
    { code: "SAKANA", codeMm: "ဆကန", nameMm: "စဉ့်ကူး" },
    { code: "SAKATA", codeMm: "စကတ", nameMm: "စဉ့်ကိုင်" },
    { code: "TAKANA", codeMm: "တကန", nameMm: "တပ်ကုန်း" },
    { code: "TATAOU", codeMm: "တတဥ", nameMm: "တံတားဦး" },
    { code: "TATHANA", codeMm: "တသန", nameMm: "တောင်သာ" },
    { code: "THAPAKA", codeMm: "သပက", nameMm: "သပိတ်ကျင်း" },
    { code: "THASANA", codeMm: "သစန", nameMm: "သာစည်" },
    { code: "WATANA", codeMm: "ဝတန", nameMm: "ဝမ်းတွင်း" },
    { code: "YAMATHA", codeMm: "ရမသ", nameMm: "ရမည်းသင်း" },
    { code: "ZABATHA", codeMm: "ဇဗသ", nameMm: "ဇမ္ဗူသီရိ" },
    { code: "ZAYATHA", codeMm: "ဇယသ", nameMm: "ဇေယျာသီရိ" },
  ],
  10: [
    { code: "BALANA", codeMm: "ဘလန", nameMm: "ဘီးလင်း" },
    { code: "KAHTANA", codeMm: "ကထန", nameMm: "ကျိုက်ထို" },
    { code: "KAKHAMA", codeMm: "ကခမ", nameMm: "ကျိုက္ခမီ" },
    { code: "KAMAYA", codeMm: "ကမရ", nameMm: "ကျိုက်မရော" },
    { code: "KHASANA", codeMm: "ခဆန", nameMm: "ချောင်းဆုံ" },
    { code: "KHAZANA", codeMm: "ခဇန", nameMm: "ခေါဇာ" },
    { code: "LAMANA", codeMm: "လမန", nameMm: "လမိုင်း" },
    { code: "MADANA", codeMm: "မဒန", nameMm: "မုဒုံ" },
    { code: "MALAMA", codeMm: "မလမ", nameMm: "မော်လမြိုင်" },
    { code: "PAMANA", codeMm: "ပမန", nameMm: "ပေါင်" },
    { code: "THAHTANA", codeMm: "သထန", nameMm: "သထုံ" },
    { code: "THAPHAYA", codeMm: "သဖရ", nameMm: "သံဖြူဇရပ်" },
    { code: "YAMANA", codeMm: "ရမန", nameMm: "ရေး" },
  ],
  11: [
    { code: "AAMANA", codeMm: "အမန", nameMm: "အမ်း" },
    { code: "BATHATA", codeMm: "ဘသတ", nameMm: "ဘူးသီးတောင်" },
    { code: "GAMANA", codeMm: "ဂမန", nameMm: "ဂွ" },
    { code: "KAPHANA", codeMm: "ကဖန", nameMm: "ကျောက်ဖြူ" },
    { code: "KATALA", codeMm: "ကတလ", nameMm: "ကျိန္တလီ" },
    { code: "KATANA", codeMm: "ကတန", nameMm: "ကျောက်တော်" },
    { code: "MAAHNA", codeMm: "မအန", nameMm: "မာန်အောင်" },
    { code: "MAAHTA", codeMm: "မအတ", nameMm: "မအီ" },
    { code: "MAOUNA", codeMm: "မဥန", nameMm: "မြောက်ဦး" },
    { code: "MAPANA", codeMm: "မပန", nameMm: "မင်းပြား" },
    { code: "MAPATA", codeMm: "မပတ", nameMm: "မြေပုံ" },
    { code: "MATANA", codeMm: "မတန", nameMm: "မောင်းတော" },
    { code: "PANAKA", codeMm: "ပဏက", nameMm: "ပုဏ္ဏကျွန်း" },
    { code: "PATANA", codeMm: "ပတန", nameMm: "ပေါက်တော" },
    { code: "SATANA", codeMm: "စတန", nameMm: "စစ်တွေ" },
    { code: "TAKANA", codeMm: "တကန", nameMm: "တောင်ကုတ်" },
    { code: "TAPAWA", codeMm: "တပဝ", nameMm: "တောင်ပြိုလက်ဝဲ" },
    { code: "THATANA", codeMm: "သတန", nameMm: "သံတွဲ" },
    { code: "YABANA", codeMm: "ရဗန", nameMm: "ရမ်းဗြဲ" },
    { code: "YATHATA", codeMm: "ရသတ", nameMm: "ရသေ့တောင်" },
  ],
  12: [
    { code: "AALANA", codeMm: "အလန", nameMm: "အလုံ" },
    { code: "AHSANA", codeMm: "အစန", nameMm: "အင်းစိန်" },
    { code: "BAHANA", codeMm: "ဗဟန", nameMm: "ဗဟန်း" },
    { code: "BATAHTA", codeMm: "ဗတထ", nameMm: "ဗိုလ်တထောင်" },
    { code: "DAGAMA", codeMm: "ဒဂမ", nameMm: "ဒဂုံမြို့သစ်(မြောက်ပိုင်း)" },
    { code: "DAGANA", codeMm: "ဒဂန", nameMm: "ဒဂုံ" },
    { code: "DAGATA", codeMm: "ဒဂတ", nameMm: "ဒဂုံမြို့သစ်(တောင်ပိုင်း)" },
    { code: "DAGAYA", codeMm: "ဒဂရ", nameMm: "ဒဂုံမြို့သစ်(အရှေ့ပိုင်း)" },
    { code: "DALANA", codeMm: "ဒလန", nameMm: "ဒလ" },
    { code: "DAPANA", codeMm: "ဒပန", nameMm: "ဒေါပုံ" },
    { code: "DASAKA", codeMm: "ဒဆက", nameMm: "ဒဂုံမြို့သစ်ဆိပ်ကမ်း" },
    { code: "HTATAPA", codeMm: "ထတပ", nameMm: "ထန်းတပင်" },
    { code: "KAKAKA", codeMm: "ကကက", nameMm: "ကိုကိုးကျွန်း" },
    { code: "KAKHAKA", codeMm: "ကခက", nameMm: "ကွမ်းခြံကုန်း" },
    { code: "KAMANA", codeMm: "ကမန", nameMm: "ကော့မှုုး" },
    { code: "KAMATA", codeMm: "ကမတ", nameMm: "ကြည့်မြင်တိုင်" },
    { code: "KAMAYA", codeMm: "ကမရ", nameMm: "ကမာရွတ်" },
    { code: "KATANA", codeMm: "ကတန", nameMm: "ကျောက်တန်း" },
    { code: "KATATA", codeMm: "ကတတ", nameMm: "ကျောက်တံတား" },
    { code: "KHAYANA", codeMm: "ခရန", nameMm: "ခရမ်း" },
    { code: "LAKANA", codeMm: "လကန", nameMm: "လှည်းကူး" },
    { code: "LAMANA", codeMm: "လမန", nameMm: "လှိုင်" },
    { code: "LAMATA", codeMm: "လမတ", nameMm: "လမ်းမတော်" },
    { code: "LATHANA", codeMm: "လသန", nameMm: "လသာ" },
    { code: "LATHAYA", codeMm: "လသယ", nameMm: "လှိုင်သာယာ" },
    { code: "MABANA", codeMm: "မဘန", nameMm: "မှော်ဘီ" },
    { code: "MAGADA", codeMm: "မဂဒ", nameMm: "မင်္ဂလာဒုံ" },
    { code: "MAGATA", codeMm: "မဂတ", nameMm: "မင်္ဂလာတောင်ညွှန့်" },
    { code: "MAYAKA", codeMm: "မရက", nameMm: "မရမ်းကုန်း" },
    { code: "OUKAMA", codeMm: "ဥကမ", nameMm: "မြောက်ဥက္ကလာပ" },
    { code: "OUKATA", codeMm: "ဥကတ", nameMm: "တောင်ဥက္ကလာပ" },
    { code: "PABATA", codeMm: "ပဘတ", nameMm: "ပန်းဘဲတန်း" },
    { code: "PAZADA", codeMm: "ပဇတ", nameMm: "ပုဇွန်တောင်" },
    { code: "SAKAKHA", codeMm: "ဆကခ", nameMm: "ဆိပ်ကြီးခနောင်တို" },
    { code: "SAKANA", codeMm: "ဆကန", nameMm: "ဆိပ်ကမ်း" },
    { code: "SAKHANA", codeMm: "စခန", nameMm: "စမ်းချောင်း" },
    { code: "TAKANA", codeMm: "တကန", nameMm: "တိုက်ကြီး" },
    { code: "TAMANA", codeMm: "တမန", nameMm: "တာမွေ" },
    { code: "TATAHTA", codeMm: "တတထ", nameMm: "တံတား" },
    { code: "TATANA", codeMm: "တတန", nameMm: "တွံတေး" },
    { code: "THAGAKA", codeMm: "သဃက", nameMm: "သင်္ဃန်းကျွန်း" },
    { code: "THAKATA", codeMm: "သကတ", nameMm: "သာကေတ" },
    { code: "THAKHANA", codeMm: "သခန", nameMm: "သုံးခွ" },
    { code: "THALANA", codeMm: "သလန", nameMm: "သန်လျင်" },
    { code: "YAKANA", codeMm: "ရကန", nameMm: "ရန်ကင်း" },
    { code: "YAPAKA", codeMm: "ရပက", nameMm: "ရွှေပေါက်ကံ" },
    { code: "YAPATHA", codeMm: "ရပသ", nameMm: "ရွှေပြည်သာ" },
  ],
  13: [
    { code: "AHPANA", codeMm: "အပန", nameMm: "အောင်ပန်း" },
    { code: "AHTANA", codeMm: "အတန", nameMm: "အင်တော" },
    { code: "AHTAYA", codeMm: "အသယ", nameMm: "အေးသာယာ" },
    { code: "HAHANA", codeMm: "ဟဟန", nameMm: "ဟဲဟိုး" },
    { code: "HAMANA", codeMm: "ဟမန", nameMm: "ဟိုမိန်း" },
    { code: "HAPANA", codeMm: "ဟပန", nameMm: "ဟိုပုံး" },
    { code: "HAPATA", codeMm: "ဟပတ", nameMm: "ဟိုပန်" },
    { code: "KAHANA", codeMm: "ကဟန", nameMm: "ကွန်ဟိန်း" },
    { code: "KAKHANA", codeMm: "ကခန", nameMm: "ကွတ်ခိုင်" },
    { code: "KALAHTA", codeMm: "ကလထ", nameMm: "ကျိူင်းလပ်" },
    { code: "KALANA", codeMm: "ကလန", nameMm: "ကလော" },
    { code: "KALATA", codeMm: "ကလတ", nameMm: "ကွမ်းလုံ" },
    { code: "KAMANA", codeMm: "ကမန", nameMm: "ကျောက်မဲ" },
    { code: "KATANA", codeMm: "ကတန", nameMm: "ကျိုင်းတုံ" },
    { code: "KATATA", codeMm: "ကတတ", nameMm: "ကျိုင်းတောင်း" },
    { code: "KATHANA", codeMm: "ကသန", nameMm: "ကျေးသီး" },
    { code: "KHAYAHA", codeMm: "ခရဟ", nameMm: "ချင်းရွှေဟော် မြို့နယ်ခွဲ" },
    { code: "LAKANA", codeMm: "လကန", nameMm: "လောက်ကိုင်" },
    { code: "LAKHANA", codeMm: "လခန", nameMm: "လင်းခေး" },
    { code: "LAKHATA", codeMm: "လခတ", nameMm: "လဲချား" },
    { code: "LALANA", codeMm: "လလန", nameMm: "လွိုင်လင်" },
    { code: "LAYANA", codeMm: "လရန", nameMm: "လားရှိုး" },
    { code: "MABANA", codeMm: "မဘန", nameMm: "မဘိမ်း" },
    { code: "MAHTANA", codeMm: "မထန", nameMm: "မော်ထိုက်" },
    { code: "MAKANA", codeMm: "မကန", nameMm: "မိုင်းကိုင်" },
    { code: "MAKHANA", codeMm: "မခန", nameMm: "မိုင်းခတ်" },
    { code: "MAKHATA", codeMm: "မခတ", nameMm: "မိုင်းခုတ်" },
    { code: "MAMATA", codeMm: "မမတ", nameMm: "မိုးမိတ်" },
    { code: "MANANA", codeMm: "မနန", nameMm: "မိုးနဲ" },
    { code: "MANGANA", codeMm: "မငန", nameMm: "မိုင်းငေါ့" },
    { code: "MAPATA", codeMm: "မပတ", nameMm: "မိုင်းပြင်း" },
    { code: "MAPHAHTA", codeMm: "မဖထ", nameMm: "မိုင်းဖျန်" },
    { code: "MAPHANA", codeMm: "မဖန", nameMm: "မိုင်းဖြတ်" },
    { code: "MASANA", codeMm: "မဆန", nameMm: "မိုင်းဆတ်" },
    { code: "MASATA", codeMm: "မဆတ", nameMm: "မူဆယ်" },
    { code: "MATATA", codeMm: "မတတ", nameMm: "မန်တုန်" },
    { code: "MAYANA", codeMm: "မရန", nameMm: "မိုင်းရှုး" },
    { code: "MAYATA", codeMm: "မရတ", nameMm: "မိုင်းရယ်" },
    { code: "NAKHANA", codeMm: "နခန", nameMm: "နမ့်ခမ်း" },
    { code: "NAKHATA", codeMm: "နခတ", nameMm: "နောင်ချို" },
    { code: "NAMATA", codeMm: "နမတ", nameMm: "နမ့်မတူ" },
    { code: "NAPANA", codeMm: "နဖန", nameMm: "နမ့်ဖိုင်" },
    { code: "NASANA", codeMm: "နဆန", nameMm: "နမ့်ဆန်" },
    { code: "NATAYA", codeMm: "နတရ", nameMm: "နောင်တရား" },
    { code: "NYAYANA", codeMm: "ညရန", nameMm: "ညောင်ရွှေ" },
    { code: "PALANA", codeMm: "ပလန", nameMm: "ပင်လုံ" },
    { code: "PAPAKA", codeMm: "ပပက", nameMm: "ပုံပါကျင်" },
    { code: "PATAYA", codeMm: "ပတရ", nameMm: "ပင်းတယ" },
    { code: "PAWANA", codeMm: "ပဝန", nameMm: "ပန်ဝိုင်" },
    { code: "PHAKHANA", codeMm: "ဖခန", nameMm: "ဖယ်ခုံ" },
    { code: "SASANA", codeMm: "ဆဆန", nameMm: "ဆီဆိုင်" },
    { code: "TAKANA", codeMm: "တကန", nameMm: "တောင်ကြီး" },
    { code: "TAKHALA", codeMm: "တခလ", nameMm: "တာချီလိတ်" },
    { code: "TALANA", codeMm: "တလန", nameMm: "တာလေ" },
    { code: "TAMANYA", codeMm: "တမည", nameMm: "တာမိုးညဲ" },
    { code: "TATANA", codeMm: "တတန", nameMm: "တုံတာ" },
    { code: "TAYANA", codeMm: "တယန", nameMm: "တန့်ယန်း" },
    { code: "THANANA", codeMm: "သနန", nameMm: "သိန္နီ" },
    { code: "THAPANA", codeMm: "သပန", nameMm: "သီပေါ" },
    { code: "YANGANA", codeMm: "ရငန", nameMm: "ရွာငံ" },
    { code: "YANYANA", codeMm: "ရညန", nameMm: "ရွှေညောင်" },
    { code: "YASANA", codeMm: "ရစန", nameMm: "ရပ်စောက်" },
  ],
  14: [
    { code: "AHGAPA", codeMm: "အဂပ", nameMm: "အင်္ဂပူ" },
    { code: "AHMANA", codeMm: "အမန", nameMm: "အိမ်မဲ" },
    { code: "AHMATA", codeMm: "အမတ", nameMm: "အမာ" },
    { code: "BAKALA", codeMm: "ဘကလ", nameMm: "ဘိုကလေး" },
    { code: "DADAYA", codeMm: "ဒဒရ", nameMm: "ဒေးဒရဲ" },
    { code: "DANAPHA", codeMm: "ဓနဖ", nameMm: "ဓနုဖြူ" },
    { code: "HAKAKA", codeMm: "ဟကက", nameMm: "ဟိုင်းကြီးကျွန်း" },
    { code: "HATHATA", codeMm: "ဟသတ", nameMm: "ဟင်္သာတ" },
    { code: "KAKAHTA", codeMm: "ကကထ", nameMm: "ကန်ကြီးထောင့်" },
    { code: "KAKANA", codeMm: "ကကန", nameMm: "ကျောင်းကုန်း" },
    { code: "KAKHANA", codeMm: "ကခန", nameMm: "ကြံခင်း" },
    { code: "KALANA", codeMm: "ကလန", nameMm: "ကျိုက်လတ်" },
    { code: "KANANA", codeMm: "ခနန", nameMm: "ခနောင်" },
    { code: "KAPANA", codeMm: "ကပန", nameMm: "ကျုံပျော်" },
    { code: "LAMANA", codeMm: "လမန", nameMm: "လေးမျက်နှာ" },
    { code: "LAPATA", codeMm: "လပတ", nameMm: "လပွတ္တာ" },
    { code: "MAAHANA", codeMm: "မအန", nameMm: "မြန်အောင်" },
    { code: "MAAHPA", codeMm: "မအပ", nameMm: "မအူပင်" },
    { code: "MAMAKA", codeMm: "မမက", nameMm: "မော်လမြိုင်ကျွန်း" },
    { code: "MAMANA", codeMm: "မမန", nameMm: "မြောင်းမြ" },
    { code: "NGAPATA", codeMm: "ငပတ", nameMm: "ငပုတော" },
    { code: "NGATHAKHA", codeMm: "ငသခ", nameMm: "ငါးသိုင်းချောင်း" },
    { code: "NGAYAKA", codeMm: "ငရက", nameMm: "ငရုတ်ကောင်း" },
    { code: "NYATANA", codeMm: "ညတန", nameMm: "ညောင်တုန်း" },
    { code: "PASALA", codeMm: "ပစလ", nameMm: "ပြင်စလူ" },
    { code: "PATANA", codeMm: "ပတန", nameMm: "ပန်းတနော်" },
    { code: "PATHANA", codeMm: "ပသန", nameMm: "ပုသိမ်(အနောက်)" },
    { code: "PATHAYA", codeMm: "ပသရ", nameMm: "ပုသိမ်(အရှေ့)" },
    { code: "PHAPANA", codeMm: "ဖပန", nameMm: "ဖျာပုံ" },
    { code: "THAPANA", codeMm: "သပန", nameMm: "သာပေါင်း" },
    { code: "WAKHAMA", codeMm: "ဝခမ", nameMm: "ဝါးခယ်မ" },
    { code: "YAKANA", codeMm: "ရကန", nameMm: "ရေကြည်" },
    { code: "YATHAYA", codeMm: "ရသယ", nameMm: "ရွှေသောင်ယံ" },
    { code: "ZALANA", codeMm: "ဇလန", nameMm: "ဇလွန်" },
  ],
};
